FROM golang:1.13

WORKDIR /go/src/github.com/eagraf/cloudworker
COPY . .

RUN go get github.com/githubnemo/CompileDaemon

RUN go get -d -v ./...
RUN go install -v ./...

CMD ["cloudworker", "ec2-54-196-13-197.compute-1.amazonaws.com"]

