FROM golang:1.13

WORKDIR /go/src/github.com/eagraf/cloudworker
COPY . .

RUN go get github.com/githubnemo/CompileDaemon

RUN go get -d -v ./...
RUN go install -v ./...

RUN go build

RUN chmod +x ./wait.sh

CMD ["./wait.sh"]